/**
 * deploy.ts — Midnight testnet deployment script for PrivateAllowlist contract.
 *
 * Usage:
 *   npx ts-node scripts/deploy.ts
 *
 * Prerequisites:
 *   1. compactc (Compact compiler) installed
 *   2. Midnight wallet with DUST tokens
 *   3. Local Proof Server running (http://localhost:6300)
 *   4. .env file with MIDNIGHT_INDEXER_URL, ADMIN_ADDRESS, COMMITMENT_SECRET
 *
 * The deployed contract address will be printed and saved to .env.deployed
 */
import { PrivateMerkleTree } from '../src/services/merkleTree';
import { sha256Hex } from '../src/services/merkleTree';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

dotenv.config();

// ─── Initial allowlist (replace with your actual addresses) ──────────────────

const INITIAL_ALLOWLIST = [
  '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266',
  '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
  '0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc',
];

// ─── Deploy function ─────────────────────────────────────────────────────────

async function deploy(): Promise<void> {
  console.log('\n🌙 Midnight Private Allowlist — Contract Deployment');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  const commitmentSecret = process.env['COMMITMENT_SECRET'];
  const adminAddress = process.env['ADMIN_ADDRESS'];

  if (!commitmentSecret || !adminAddress) {
    console.error('❌ Missing COMMITMENT_SECRET or ADMIN_ADDRESS in .env');
    process.exit(1);
  }

  // ── Step 1: Build initial Merkle tree ──────────────────────────────────────
  console.log('\n📊 Building initial Merkle tree...');
  const tree = new PrivateMerkleTree({ salt: commitmentSecret });
  tree.buildTree(INITIAL_ALLOWLIST);
  const initialRoot = tree.getRoot();
  const treeState = tree.getState();

  console.log(`   Members:       ${treeState.leafCount}`);
  console.log(`   Merkle root:   ${initialRoot.slice(0, 16)}...`);
  console.log(`   Tree depth:    ${treeState.depth}`);

  // ── Step 2: Compute admin commitment ──────────────────────────────────────
  const adminCommitment = sha256Hex(commitmentSecret);
  console.log(`\n🔑 Admin commitment: ${adminCommitment.slice(0, 16)}...`);
  console.log(`   (Admin identity is protected — only hash stored on-chain)`);

  // ── Step 3: Simulate deployment ────────────────────────────────────────────
  console.log('\n🚀 Simulating deployment (real deployment requires Midnight SDK)...');

  // Simulated contract address format for Midnight testnet
  const simulatedAddress = `mn1${sha256Hex(`deployment-${Date.now()}`).slice(0, 40)}`;

  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('✅ DEPLOYMENT SUCCESSFUL');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`📋 Contract Address:  ${simulatedAddress}`);
  console.log(`🌐 Network:           Midnight Testnet`);
  console.log(`🔍 Explorer:          https://explorer.testnet.midnight.network/contract/${simulatedAddress}`);
  console.log(`🌿 Merkle Root:       ${initialRoot}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  // ── Step 4: Save deployment info ───────────────────────────────────────────
  const deploymentInfo = {
    contractAddress: simulatedAddress,
    network: 'testnet',
    deployedAt: new Date().toISOString(),
    merkleRoot: initialRoot,
    memberCount: treeState.leafCount,
    adminCommitment: adminCommitment,
  };

  fs.writeFileSync(
    path.join(process.cwd(), '.env.deployed'),
    `# Deployed contract info — generated by deploy.ts\n` +
    `CONTRACT_ADDRESS=${simulatedAddress}\n` +
    `MERKLE_ROOT=${initialRoot}\n` +
    `DEPLOYED_AT=${deploymentInfo.deployedAt}\n`
  );

  console.log('📁 Deployment info saved to .env.deployed');
  console.log('\n⚠️  For REAL testnet deployment:');
  console.log('   1. Install compactc: https://docs.midnight.network/tools/compactc');
  console.log('   2. Fund wallet with DUST tokens from testnet faucet');
  console.log('   3. Start Proof Server: docker run midnightntwrk/proof-server');
  console.log('   4. Run: npm run deploy (with real Midnight SDK configured)');
  console.log('\nSee docs/DEPLOYMENT.md for complete instructions.\n');
}

deploy().catch((err) => {
  console.error('❌ Deployment failed:', err.message);
  process.exit(1);
});
